/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.dimed.avro;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Assinatura extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6983691176432923251L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Assinatura\",\"namespace\":\"example\",\"fields\":[{\"name\":\"idAssinatura\",\"type\":\"long\"},{\"name\":\"hostname\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public long idAssinatura;
  @Deprecated public java.lang.String hostname;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Assinatura() {}

  /**
   * All-args constructor.
   * @param idAssinatura The new value for idAssinatura
   * @param hostname The new value for hostname
   */
  public Assinatura(java.lang.Long idAssinatura, java.lang.String hostname) {
    this.idAssinatura = idAssinatura;
    this.hostname = hostname;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return idAssinatura;
    case 1: return hostname;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: idAssinatura = (java.lang.Long)value$; break;
    case 1: hostname = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'idAssinatura' field.
   * @return The value of the 'idAssinatura' field.
   */
  public java.lang.Long getIdAssinatura() {
    return idAssinatura;
  }

  /**
   * Sets the value of the 'idAssinatura' field.
   * @param value the value to set.
   */
  public void setIdAssinatura(java.lang.Long value) {
    this.idAssinatura = value;
  }

  /**
   * Gets the value of the 'hostname' field.
   * @return The value of the 'hostname' field.
   */
  public java.lang.String getHostname() {
    return hostname;
  }

  /**
   * Sets the value of the 'hostname' field.
   * @param value the value to set.
   */
  public void setHostname(java.lang.String value) {
    this.hostname = value;
  }

  /**
   * Creates a new Assinatura RecordBuilder.
   * @return A new Assinatura RecordBuilder
   */
  public static Assinatura.Builder newBuilder() {
    return new Assinatura.Builder();
  }

  /**
   * Creates a new Assinatura RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Assinatura RecordBuilder
   */
  public static Assinatura.Builder newBuilder(Assinatura.Builder other) {
    return new Assinatura.Builder(other);
  }

  /**
   * Creates a new Assinatura RecordBuilder by copying an existing Assinatura instance.
   * @param other The existing instance to copy.
   * @return A new Assinatura RecordBuilder
   */
  public static Assinatura.Builder newBuilder(Assinatura other) {
    return new Assinatura.Builder(other);
  }

  /**
   * RecordBuilder for Assinatura instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Assinatura>
    implements org.apache.avro.data.RecordBuilder<Assinatura> {

    private long idAssinatura;
    private java.lang.String hostname;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Assinatura.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.idAssinatura)) {
        this.idAssinatura = data().deepCopy(fields()[0].schema(), other.idAssinatura);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.hostname)) {
        this.hostname = data().deepCopy(fields()[1].schema(), other.hostname);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Assinatura instance
     * @param other The existing instance to copy.
     */
    private Builder(Assinatura other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.idAssinatura)) {
        this.idAssinatura = data().deepCopy(fields()[0].schema(), other.idAssinatura);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.hostname)) {
        this.hostname = data().deepCopy(fields()[1].schema(), other.hostname);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'idAssinatura' field.
      * @return The value.
      */
    public java.lang.Long getIdAssinatura() {
      return idAssinatura;
    }

    /**
      * Sets the value of the 'idAssinatura' field.
      * @param value The value of 'idAssinatura'.
      * @return This builder.
      */
    public Assinatura.Builder setIdAssinatura(long value) {
      validate(fields()[0], value);
      this.idAssinatura = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'idAssinatura' field has been set.
      * @return True if the 'idAssinatura' field has been set, false otherwise.
      */
    public boolean hasIdAssinatura() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'idAssinatura' field.
      * @return This builder.
      */
    public Assinatura.Builder clearIdAssinatura() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'hostname' field.
      * @return The value.
      */
    public java.lang.String getHostname() {
      return hostname;
    }

    /**
      * Sets the value of the 'hostname' field.
      * @param value The value of 'hostname'.
      * @return This builder.
      */
    public Assinatura.Builder setHostname(java.lang.String value) {
      validate(fields()[1], value);
      this.hostname = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'hostname' field has been set.
      * @return True if the 'hostname' field has been set, false otherwise.
      */
    public boolean hasHostname() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'hostname' field.
      * @return This builder.
      */
    public Assinatura.Builder clearHostname() {
      hostname = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public Assinatura build() {
      try {
        Assinatura record = new Assinatura();
        record.idAssinatura = fieldSetFlags()[0] ? this.idAssinatura : (java.lang.Long) defaultValue(fields()[0]);
        record.hostname = fieldSetFlags()[1] ? this.hostname : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
